name: Deploy React Portfolio to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: portfolio

      - name: Build Project
        run: npm run build
        working-directory: portfolio

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # change if bucket is in another region

      - name: Deploy to S3
        run: |
          echo "Checking dist folder..."
          ls -la portfolio/dist || echo "dist folder missing!"
          echo "Deploying to S3..."
          aws s3 sync portfolio/dist s3://portfolioreact-aws \
            --delete \
            --exact-timestamps
